name = "korea-weather-bot"
main = "src/index.ts"
compatibility_date = "2025-09-01"

kv_namespaces = [
  { binding = "USERS", id = "2987663ff047423aad70f3d909587f6a" }
]

[triggers]
crons = ["0 22 * * *"]
